### ISSUE TITLE
Vueperslides in Astro Build issue 

### ISSUE THREAD

**Issue by midlantica** [antoniandre/vueper-slides#186]
`> npm run build

> @example/basics@0.0.1 build
> astro build

11:44:45 PM [build] output target: static
11:44:45 PM [build] Collecting build info...
11:44:45 PM [build] Completed in 577ms.
11:44:45 PM [build] Building static entrypoints...
11:44:48 PM [build] Completed in 3.00s.

 building client 
Completed in 1.02s.

 generating static routes 
 error   Named export 'VueperSlide' not found. The requested module 'vueperslides' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'vueperslides';
  const { VueperSlides, VueperSlide } = pkg;
  
file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/dist/entry.mjs?time=1662266689397:4
/* empty css                        */import { VueperSlides, VueperSlide } from 'vueperslides';
                                                             ^^^^^^^^^^^
SyntaxError: Named export 'VueperSlide' not found. The requested module 'vueperslides' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vueperslides';
const { VueperSlides, VueperSlide } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:341:24)
    at async generatePages (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/core/build/generate.js:70:20)
    at async staticBuild (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/core/build/static-build.js:67:5)
    at async AstroBuilder.build (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/core/build/index.js:82:5)
    at async AstroBuilder.run (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/core/build/index.js:123:7)
    at async build (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///Users/andrew/Documents/_work/_roger-ivens/rogerivens.com/node_modules/astro/dist/cli/index.js:138:14)
 ~/Documents/_work/_roger-ivens/rogerivens.com | master >1 !3 .............................................................................................................................................. 8s 
> `

**Comment by midlantica** [comment]
Vueperslides is great. All is well in npm run dev. But when I run npm run build in Astro it fails.

https://github.com/midlantica/rogerivens.com
